### ISSUE TITLE
TemporalInterval and other time classes

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-pg-parser-networkx#27]
Working on the `filter_temporal` process in `openeo-processes-dask` I noticed that the TemporalInterval class can't handle open intervals, like:

```python
from openeo_pg_parser_networkx.pg_schema import TemporalInterval
interval=["2018-05-01", None]
tobj = TemporalInterval.parse_obj(interval)

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Input In [11], in <cell line: 3>()
      1 from openeo_pg_parser_networkx.pg_schema import TemporalInterval
      2 interval=["2018-05-01", None]
----> 3 tobj = TemporalInterval.parse_obj(interval)

File ~\Miniconda3\envs\sap\lib\site-packages\pydantic\main.py:526, in pydantic.main.BaseModel.parse_obj()

File ~\Miniconda3\envs\sap\lib\site-packages\pydantic\main.py:342, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for TemporalInterval
__root__ -> 1
  none is not an allowed value (type=type_error.none.not_allowed)
```

Additionally, what is the benefit of having custom temporal classes instead of using directly numpy.datetime?

**Comment by LukeWeidenwalker** [comment]
Ah, good catch, yes, we should totally address this!

> Additionally, what is the benefit of having custom temporal classes instead of using directly numpy.datetime?

It would be much better if we could directly parse to the right numpy datetime objects because these could then be used in the processes directly. However, we need to ensure that the regex is validated against and that it's parsed as RFC 3339. I.e. if in `TemporalInterval`, we did something like `__root__: list[Union[np.datetime64]]`, this wouldn't do this validation and either fail or (worse) parse in unexpected ways. In fact the parsing as RFC 3339 was the reason why I opted for pendulum here, I didn't want to go down the time-representation rabbit hole and it was the only datetime library that did this out of the box. Therefore I think we need this intermediate pydantic class to make sure this is considered during parsing at all. 

Would love to stand corrected though, this part of the code has always felt a bit awkward to me. My preferred outcome would also be that we don't have to import these custom types in openeo-processes-dask, and instead directly resolve to the correct np.datetime and np.timedelta objects here. If you can think of a nice way to do this, I'd love to hear about it! ;)

**Comment by LukeWeidenwalker** [comment]
I've also opened https://github.com/Open-EO/openeo-pg-parser-networkx/pull/30, if you could have a quick look!
